# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.participant import Participant  # noqa: F401,E501
from swagger_server.models.tag import Tag  # noqa: F401,E501
from swagger_server import util


class Treaty(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, chapter_id: int=None, tags: List[Tag]=None, participants: List[Participant]=None, status: str=None):  # noqa: E501
        """Treaty - a model defined in Swagger

        :param id: The id of this Treaty.  # noqa: E501
        :type id: int
        :param name: The name of this Treaty.  # noqa: E501
        :type name: str
        :param chapter_id: The chapter_id of this Treaty.  # noqa: E501
        :type chapter_id: int
        :param tags: The tags of this Treaty.  # noqa: E501
        :type tags: List[Tag]
        :param participants: The participants of this Treaty.  # noqa: E501
        :type participants: List[Participant]
        :param status: The status of this Treaty.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'chapter_id': int,
            'tags': List[Tag],
            'participants': List[Participant],
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'chapter_id': 'chapterId',
            'tags': 'tags',
            'participants': 'participants',
            'status': 'status'
        }

        self._id = id
        self._name = name
        self._chapter_id = chapter_id
        self._tags = tags
        self._participants = participants
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Treaty':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Treaty of this Treaty.  # noqa: E501
        :rtype: Treaty
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Treaty.


        :return: The id of this Treaty.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Treaty.


        :param id: The id of this Treaty.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Treaty.


        :return: The name of this Treaty.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Treaty.


        :param name: The name of this Treaty.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def chapter_id(self) -> int:
        """Gets the chapter_id of this Treaty.


        :return: The chapter_id of this Treaty.
        :rtype: int
        """
        return self._chapter_id

    @chapter_id.setter
    def chapter_id(self, chapter_id: int):
        """Sets the chapter_id of this Treaty.


        :param chapter_id: The chapter_id of this Treaty.
        :type chapter_id: int
        """
        if chapter_id is None:
            raise ValueError("Invalid value for `chapter_id`, must not be `None`")  # noqa: E501

        self._chapter_id = chapter_id

    @property
    def tags(self) -> List[Tag]:
        """Gets the tags of this Treaty.


        :return: The tags of this Treaty.
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[Tag]):
        """Sets the tags of this Treaty.


        :param tags: The tags of this Treaty.
        :type tags: List[Tag]
        """

        self._tags = tags

    @property
    def participants(self) -> List[Participant]:
        """Gets the participants of this Treaty.


        :return: The participants of this Treaty.
        :rtype: List[Participant]
        """
        return self._participants

    @participants.setter
    def participants(self, participants: List[Participant]):
        """Sets the participants of this Treaty.


        :param participants: The participants of this Treaty.
        :type participants: List[Participant]
        """

        self._participants = participants

    @property
    def status(self) -> str:
        """Gets the status of this Treaty.

        status of a treaty  # noqa: E501

        :return: The status of this Treaty.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Treaty.

        status of a treaty  # noqa: E501

        :param status: The status of this Treaty.
        :type status: str
        """
        allowed_values = ["pending", "entered into force"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
